MinhasDespesas/urls.py
from django.urls import path
from despesas import views

urlpatterns = [
    path('grupo_despesas/', views.grupo_despesas_form, name='grupo_despesas_form'),
    path('despesa/', views.despesa_form, name='despesa_form'),
    path('listagem/', views.listar_despesas, name='listagem'),
    path('excluir_despesa/<int:despesa_id>/', views.excluir_despesa, name='excluir_despesa'),
    path('alterar_despesa/<int:despesa_id>/', views.alterar_despesa, name='alterar_despesa'),
    path('excluir_grupo_despesas/<int:grupo_id>/', views.excluir_grupo_despesas, name='excluir_grupo_despesas'),
    path('alterar_grupo_despesas/<int:grupo_id>/', views.alterar_grupo_despesas, name='alterar_grupo_despesas'),
    path('relatorios/', views.relatorios, name='relatorios'),
    path('relatorio_despesas_por_grupo/', views.relatorio_despesas_por_grupo, name='relatorio_despesas_por_grupo'),
    path('relatorio_geral/', views.relatorio_geral, name='relatorio_geral'),
    path('plano_de_contas/', views.plano_de_contas, name='plano_de_contas'),
]

despesas/models.py
from django.db import models

class GrupoDespesas(models.Model):
    nome = models.CharField(max_length=100, null=False)  

    class Meta:
        db_table = 'grupodespesas'  
        
    def __str__(self):
        return self.nome

class Despesa(models.Model):
    grupo = models.ForeignKey(GrupoDespesas, on_delete=models.CASCADE)
    nome = models.CharField(max_length=100)
    vencimento = models.DateField()
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    data_pagamento = models.DateField(null=True, blank=True)
    valor_pago = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    observacao = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.nome

    class Meta:
        managed = False
        db_table = 'despesa'

despesas/forms.py
from django import forms
from .models import GrupoDespesas, Despesa

class GrupoDespesasForm(forms.ModelForm):
    class Meta:
        model = GrupoDespesas
        fields = ['nome']

class DespesaForm(forms.ModelForm):
    class Meta:
        model = Despesa
        fields = ['grupo', 'nome', 'vencimento', 'valor', 'data_pagamento', 'valor_pago', 'observacao']
        
    grupo = forms.ModelChoiceField(queryset=GrupoDespesas.objects.all(), empty_label="Selecione um grupo")
    nome = forms.CharField(max_length=100)
    vencimento = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    valor = forms.DecimalField(max_digits=10, decimal_places=2)
    data_pagamento = forms.DateField(required=False, widget=forms.DateInput(attrs={'type': 'date'}))
    valor_pago = forms.DecimalField(max_digits=10, decimal_places=2, required=False)
    observacao = forms.CharField(widget=forms.Textarea, required=False)

despesas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ValidationError
from .models import GrupoDespesas, Despesa
from django.http import JsonResponse
from django.middleware import csrf
from django.utils.dateparse import parse_date
from django.utils import timezone
from django.db.models import Sum, Min ,Max, Count
from django.db.models.functions import TruncMonth
from django.contrib import messages
from datetime import datetime
import matplotlib.pyplot as plt
from collections import defaultdict
import numpy as np
import base64
import io
from io import BytesIO

def grupo_despesas_form(request):
    if request.method == 'POST':
        nome = request.POST.get('nome')
        if nome:
            if GrupoDespesas.objects.filter(nome=nome).exists():
                messages.error(request, "Esse grupo de despesas já existe.")
            else:
                GrupoDespesas.objects.create(nome=nome)
                messages.success(request, "Grupo de despesas cadastrado com sucesso!")
            return redirect('grupo_despesas_form')

    grupos = GrupoDespesas.objects.all()
    return render(request, 'grupo_despesas_form.html', {'grupos': grupos})

def despesa_form(request):
    if request.method == 'POST':
        grupo_id = request.POST.get('grupo_id')
        nome = request.POST.get('nome')
        vencimento = request.POST.get('vencimento')
        valor = request.POST.get('valor')
        data_pagamento = request.POST.get('data_pagamento')
        valor_pago = request.POST.get('valor_pago')
        observacao = request.POST.get('observacao')

        try:
            despesa = Despesa(
                grupo_id=grupo_id,
                nome=nome,
                vencimento=vencimento,
                valor=valor,
                data_pagamento=data_pagamento if data_pagamento else None,
                valor_pago=valor_pago if valor_pago else None,
                observacao=observacao
            )
            despesa.full_clean()
            despesa.save()
            return redirect('despesa_form')
        except ValidationError as e:
            return render(request, 'despesa_form.html', {'grupos': GrupoDespesas.objects.all(), 'errors': e.messages})

    grupos = GrupoDespesas.objects.all()
    return render(request, 'despesa_form.html', {'grupos': grupos})

def listar_despesas(request):
    filtro_nome = request.GET.get('filtro_nome', '')
    data_inicio = request.GET.get('data_inicio', '')
    data_fim = request.GET.get('data_fim', '')
    filtro_estado = request.GET.get('filtro_estado', 'todas')
    filtro_grupo = request.GET.get('filtro_grupo', '')

    despesas = Despesa.objects.all().order_by('-vencimento')

    if filtro_nome:
        despesas = despesas.filter(nome__icontains=filtro_nome)

    if data_inicio:
        data_inicio = parse_date(data_inicio)
        if data_inicio:
            despesas = despesas.filter(vencimento__gte=data_inicio)

    if data_fim:
        data_fim = parse_date(data_fim)
        if data_fim:
            despesas = despesas.filter(vencimento__lte=data_fim)

    if filtro_estado == 'abertas':
        despesas = despesas.filter(data_pagamento__isnull=True)
    elif filtro_estado == 'pagas':
        despesas = despesas.filter(data_pagamento__isnull=False)

    if filtro_grupo:
        despesas = despesas.filter(grupo_id=filtro_grupo)

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        despesas_list = [
            {
                'id': despesa.id,
                'nome': despesa.nome,
                'grupo': despesa.grupo.nome,
                'vencimento': despesa.vencimento.strftime('%Y-%m-%d'),
                'valor': despesa.valor,
                'data_pagamento': despesa.data_pagamento.strftime('%Y-%m-%d') if despesa.data_pagamento else '',
                'valor_pago': despesa.valor_pago if despesa.valor_pago else '0.00',
                'observacao': despesa.observacao,
            }
            for despesa in despesas
        ]
        return JsonResponse({'despesas': despesas_list, 'csrf_token': csrf.get_token(request)})
    
    grupos = GrupoDespesas.objects.all()
    return render(request, 'listagem.html', {'despesas': despesas, 'grupos': grupos})

def excluir_despesa(request, despesa_id):
    despesa = get_object_or_404(Despesa, pk=despesa_id)
    
    if request.method == 'POST':
        despesa.delete()
        return redirect('listagem')

    return redirect('listagem')

def alterar_despesa(request, despesa_id):
    despesa = get_object_or_404(Despesa, pk=despesa_id)
    grupos = GrupoDespesas.objects.all()

    if request.method == 'POST':
        despesa.grupo_id = request.POST.get('grupo_id')
        despesa.nome = request.POST.get('nome')
        despesa.vencimento = request.POST.get('vencimento')
        despesa.valor = request.POST.get('valor')

        data_pagamento = request.POST.get('data_pagamento')
        despesa.data_pagamento = data_pagamento if data_pagamento else None

        valor_pago = request.POST.get('valor_pago')
        despesa.valor_pago = valor_pago if valor_pago else None

        despesa.observacao = request.POST.get('observacao')
        
        despesa.save()
        return redirect('listagem')

    return render(request, 'alterar.html', {'despesa': despesa, 'grupos': grupos})

def excluir_grupo_despesas(request, grupo_id):
    grupo = get_object_or_404(GrupoDespesas, pk=grupo_id)

    if request.method == 'POST':
        grupo.delete()
        return redirect('grupo_despesas_form')

    return redirect('grupo_despesas_form')

def alterar_grupo_despesas(request, grupo_id):
    grupo = get_object_or_404(GrupoDespesas, pk=grupo_id)
    
    if request.method == 'POST':
        nome = request.POST.get('nome')
        if nome:
            grupo.nome = nome
            grupo.save()
            return redirect('grupo_despesas_form')
    
    return render(request, 'alterar_grupo_despesas.html', {'grupo': grupo})

def relatorios(request):
    return render(request, 'relatorios.html')

def relatorio_despesas_por_grupo(request):
    grupo_id = request.GET.get('grupo_id')
    total_pago = None
    total_em_aberto = None
    percentual = None
    despesas_pagas_por_mes = []
    despesas_abertas_por_mes = []

    grupos = GrupoDespesas.objects.all()

    if grupo_id:
        despesas_grupo = Despesa.objects.filter(grupo_id=grupo_id)

        despesas_pagas = despesas_grupo.filter(data_pagamento__isnull=False).annotate(month=TruncMonth('vencimento')).values('month').annotate(total=Sum('valor')).order_by('month')
        despesas_abertas = despesas_grupo.filter(data_pagamento__isnull=True).annotate(month=TruncMonth('vencimento')).values('month').annotate(total=Sum('valor')).order_by('month')
        
        # Dados do Gráfico
        meses = sorted(set(despesa['month'] for despesa in despesas_pagas) | set(despesa['month'] for despesa in despesas_abertas))
        despesas_pagas_por_mes = {mes: 0 for mes in meses}
        despesas_abertas_por_mes = {mes: 0 for mes in meses}

        for despesa in despesas_pagas:
            despesas_pagas_por_mes[despesa['month']] = despesa['total']

        for despesa in despesas_abertas:
            despesas_abertas_por_mes[despesa['month']] = despesa['total']

        meses = [mes.strftime('%m/%Y') for mes in meses]
        valores_pagos = [despesas_pagas_por_mes[mes] for mes in despesas_pagas_por_mes]
        valores_abertos = [despesas_abertas_por_mes[mes] for mes in despesas_abertas_por_mes]

        # Gráfico de Barras
        x = np.arange(len(meses))
        bar_width = 0.3 if len(meses) <= 3 else 0.4  # Ajuste dinâmico da largura das barras

        plt.figure(figsize=(10, 5))
        bars_pagos = plt.bar(x - bar_width/2, valores_pagos, width=bar_width, label='Despesas Pagas', color='#5A9')
        bars_abertos = plt.bar(x + bar_width/2, valores_abertos, width=bar_width, label='Despesas Abertas', color='#FF5733')
        
        plt.xlabel('Mês de Vencimento')
        plt.ylabel('Valor R$')
        plt.title('Despesas Pagas e Abertas por Mês')
        plt.legend()
        plt.xticks(ticks=x, labels=meses, rotation=45)
        plt.xlim(-0.5, len(meses) - 0.5)  
        plt.tight_layout()

        # Adicionar valores em cima das barras
        for bar in bars_pagos:
            yval = bar.get_height()
            plt.text(bar.get_x() + bar.get_width()/2, yval, f'{yval:.2f}', ha='center', va='bottom')

        for bar in bars_abertos:
            yval = bar.get_height()
            plt.text(bar.get_x() + bar.get_width()/2, yval, f'{yval:.2f}', ha='center', va='bottom')

        buffer = BytesIO()
        plt.savefig(buffer, format='png')
        buffer.seek(0)
        image_png = buffer.getvalue()
        buffer.close()

        grafico_base64 = base64.b64encode(image_png).decode('utf-8')

        despesas_grupo_total_pago = despesas_grupo.filter(data_pagamento__isnull=False).aggregate(total=Sum('valor_pago'))['total'] or 0
        total_geral_pago = Despesa.objects.filter(data_pagamento__isnull=False).aggregate(total=Sum('valor_pago'))['total'] or 0

        if total_geral_pago > 0:
            percentual = round((despesas_grupo_total_pago / total_geral_pago) * 100, 2)

        total_pago = round(despesas_grupo_total_pago, 2)
        total_em_aberto = round(despesas_grupo.filter(data_pagamento__isnull=True).aggregate(total=Sum('valor'))['total'] or 0, 2)

    context = {
        'grupos': grupos,
        'total_pago': total_pago,
        'total_em_aberto': total_em_aberto,
        'percentual': percentual,
        'grupo_id': grupo_id,
        'grafico_base64': grafico_base64 if grupo_id else None,
    }

    return render(request, 'relatorio_despesas_por_grupo.html', context)

def relatorio_geral(request):
    grupos = GrupoDespesas.objects.all()
    valores_totais = [Despesa.objects.filter(grupo=grupo).aggregate(Sum('valor'))['valor__sum'] or 0 for grupo in grupos]

    #gráfico de barras

despesas/templates/alterar.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alterar Despesa</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f9f9f9;
        }

        header {
            display: flex;
            justify-content: space-around;
            align-items: center;
            background-color: #5A9;
            padding: 15px;
        }

        header a {
            text-decoration: none;
            padding: 10px 20px;
            color: #fff;
            background-color: #5A9;
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        header a:hover {
            background-color: #4A8;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: white;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
            color: #333;
        }

        form {
            display: flex;
            flex-direction: column;
            gap: 15px;
        }

        label {
            font-weight: bold;
            margin-bottom: 5px;
        }

        input[type="text"],
        input[type="date"],
        input[type="number"],
        select,
        textarea {
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            width: 100%;
            box-sizing: border-box;
        }

        input[type="submit"] {
            background-color: #6C7;
            color: white;
            border: none;
            padding: 10px;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s;
        }

        input[type="submit"]:hover {
            background-color: #5A9;
        }
    </style>
</head>
<body>
    <header>
        <a href="{% url 'grupo_despesas_form' %}">Cadastro de Grupos de Despesas</a>
        <a href="{% url 'despesa_form' %}">Cadastro de Despesas</a>
        <a href="{% url 'listagem' %}">Listagem de Despesas</a>
        <a href="{% url 'relatorios' %}">Relatórios</a>
    </header>
    <div class="container">
        <h1>Alterar Despesa</h1>
        <form method="post">
            {% csrf_token %}
            <label for="grupo">Grupo:</label>
            <select id="grupo" name="grupo_id">
                {% for grupo in grupos %}
                    <option value="{{ grupo.id }}" {% if despesa.grupo_id == grupo.id %} selected {% endif %}>{{ grupo.nome }}</option>
                {% endfor %}
            </select>

            <label for="nome">Nome:</label>
            <input type="text" id="nome" name="nome" value="{{ despesa.nome }}" required>

            <label for="vencimento">Vencimento:</label>
            <input type="date" id="vencimento" name="vencimento" value="{{ despesa.vencimento|date:"Y-m-d" }}" required>

            <label for="valor">Valor:</label>
            <input type="number" step="0.01" id="valor" name="valor" value="{{ despesa.valor }}" required>

            <label for="data_pagamento">Data de Pagamento:</label>
            <input type="date" id="data_pagamento" name="data_pagamento" value="{{ despesa.data_pagamento|date:"Y-m-d" }}">

            <label for="valor_pago">Valor Pago:</label>
            <input type="number" step="0.01" id="valor_pago" name="valor_pago" value="{{ despesa.valor_pago }}">

            <label for="observacao">Observação:</label>
            <textarea id="observacao" name="observacao">{{ despesa.observacao }}</textarea>

            <input type="submit" value="Alterar">
        </form>
    </div>
</body>
</html>

despesas/templates/alterar_grupo_despesas.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alterar Grupo de Despesas</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f9f9f9;
        }

        header {
            display: flex;
            justify-content: space-around;
            align-items: center;
            background-color: #5A9;
            padding: 15px;
        }

        header a {
            text-decoration: none;
            padding: 10px 20px;
            color: #fff;
            background-color: #5A9;
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        header a:hover {
            background-color: #4A8;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: white;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            text-align: center;
            color: #333;
        }
        form {
            display: flex;
            flex-direction: column;
            gap: 15px;
        }
        label {
            font-weight: bold;
            margin-bottom: 5px;
        }

        input[type="text"],
        input[type="date"],
        input[type="number"],
        select,
        textarea {
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            width: 100%;
        }

        input[type="submit"] {
            background-color: #6C7;
            color: white;
            border: none;
            padding: 10px;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s;
        }

        input[type="submit"]:hover {
            background-color: #5A9;
        }
    </style>
</head>
<body>
    <header>
        <a href="{% url 'grupo_despesas_form' %}">Cadastro de Grupos de Despesas</a>
        <a href="{% url 'despesa_form' %}">Cadastro de Despesas</a>
        <a href="{% url 'listagem' %}">Listagem de Despesas</a>
        <a href="{% url 'relatorios' %}">Relatórios</a>
    </header>
    <div class="container">
        <h1>Alterar Grupo de Despesas</h1>
        <form method="post">
            {% csrf_token %}
            <label for="id_nome">Nome:</label><br>
            <input type="text" id="id_nome" name="nome" value="{{ grupo.nome }}" required><br><br>
            <input type="submit" value="Salvar">
        </form>
    </div>
</body>
</html>

despesas/templates/despesa_form.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registrar Despesa</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f9f9f9;
        }

        header {
            display: flex;
            justify-content: space-around;
            align-items: center;
            background-color: #5A9;
            padding: 15px;
        }

        header a {
            text-decoration: none;
            padding: 10px 20px;
            color: #fff;
            background-color: #5A9;
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        header a:hover {
            background-color: #4A8;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: white;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            color: #333;
            text-align: center;
        }

        form {
            display: flex;
            flex-direction: column;
            gap: 15px;
        }

        label {
            font-weight: bold;
            margin-bottom: 5px;
        }

        input[type="text"],
        input[type="date"],
        input[type="number"],
        select,
        textarea {
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            width: 100%;
        }

        input[type="submit"] {
            background-color: #6C7;
            color: white;
            border: none;
            padding: 10px;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s;
        }

        input[type="submit"]:hover {
            background-color: #4A8;
        }

        ul {
            list-style-type: none;
            padding: 0;
            margin: 20px 0;
            color: red;
        }

        ul li {
            margin: 5px 0;
        }
        
        input[type="text"],
        input[type="date"],
        input[type="number"],
        select,
        textarea {
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            width: 100%;
            box-sizing: border-box; 
        }
    </style>
    <script>
        function toggleValorPago() {
            const dataPagamento = document.getElementById('data_pagamento').value;
            const valorPago = document.getElementById('valor_pago');
            if (dataPagamento) {
                valorPago.disabled = false;
            } else {
                valorPago.value = '';  //limpa o campo se a data de pagamento for removida
                valorPago.disabled = true;
            }
        }

        function showAlert() {
            alert("Despesa Cadastrada");
        }
    </script>
</head>
<body>
    <header>
        <a href="{% url 'grupo_despesas_form' %}">Cadastro de Grupos de Despesas</a>
        <a href="{% url 'despesa_form' %}">Cadastro de Despesas</a>
        <a href="{% url 'listagem' %}">Listagem de Despesas</a>
        <a href="{% url 'relatorios' %}">Relatórios</a>
    </header>
    <div class="container">
        <h1>Registrar Despesa</h1>
        <form method="post" onsubmit="showAlert()">
            {% csrf_token %}
            <label for="grupo">Grupo:</label>
            <select id="grupo" name="grupo_id">
                {% for grupo in grupos %}
                    <option value="{{ grupo.id }}">{{ grupo.nome }}</option>
                {% endfor %}
            </select>

            <label for="nome">Nome:</label>
            <input type="text" id="nome" name="nome" required>

            <label for="vencimento">Vencimento:</label>
            <input type="date" id="vencimento" name="vencimento" required>

            <label for="valor">Valor:</label>
            <input type="number" step="0.01" id="valor" name="valor" required>

            <label for="data_pagamento">Data de Pagamento:</label>
            <input type="date" id="data_pagamento" name="data_pagamento" onchange="toggleValorPago()">

            <label for="valor_pago">Valor Pago:</label>
            <input type="number" step="0.01" id="valor_pago" name="valor_pago" disabled>

            <label for="observacao">Observação:</label>
            <textarea id="observacao" name="observacao"></textarea>

            <input type="submit" value="Registrar">
        </form>
        {% if errors %}
        <ul>
            {% for error in errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</body>
</html>

despesas/templates/grupo_despesas_form.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registrar Grupo de Despesas</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f9f9f9;
        }
        header {
            display: flex;
            justify-content: space-around;
            align-items: center;
            background-color: #5A9;
            padding: 15px;
        }

        header a {
            text-decoration: none;
            padding: 10px 20px;
            color: #fff;
            background-color: #5A9;
            border-radius: 5px;
            transition: background-color 0.3s;
        }
        header a:hover {
            background-color: #4A8;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }

        h1, h2 {
            color: #333;
        }

        form {
            display: flex;
            flex-direction: column;
            gap: 10px;
        }

        label, input[type="text"], input[type="submit"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
        }
        
        input[type="submit"] {
            background-color: #6C7;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        input[type="submit"]:hover {
            background-color: #5A9;
        }
        table {
            width: 100%;
            margin: 20px 0;
            border-collapse: collapse;
            background-color: white;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        th, td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f2f2f2;
        }
        td form {
            display: inline;
        }
        td button {
            padding: 5px 10px;
            background-color: #6C7;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s;
        }
        td button:hover {
            background-color: #5A9;
        }
    </style>
    <script>
        function confirmarExclusao() {
            return confirm("Tem certeza que deseja excluir este grupo de despesas? Todas as despesas associadas também serão excluídas.");
        }
    </script>
</head>
<body>
    <header>
        <a href="{% url 'grupo_despesas_form' %}">Cadastro de Grupos de Despesas</a>
        <a href="{% url 'despesa_form' %}">Cadastro de Despesas</a>
        <a href="{% url 'listagem' %}">Listagem de Despesas</a>
        <a href="{% url 'relatorios' %}">Relatórios</a>
    </header>
    <div class="container">
        <h1>Registrar Grupo de Despesas</h1>
        <form method="post">
            {% csrf_token %}
            <label for="id_nome">Nome:</label>
            <input type="text" id="id_nome" name="nome" required>
            <input type="submit" value="Registrar">
        </form>
        
        <h2>Lista de Grupos</h2>
        {% if messages %}
                {% for message in messages %}
                    <h4 style="color: {% if message.tags == 'error' %}red{% elif message.tags == 'success' %}green{% endif %};">
                        {{ message }}</h4>
                {% endfor %}
        {% endif %}
        <table>
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for grupo in grupos %}
                <tr>
                    <td>{{ grupo.nome }}</td>
                    <td>
                        <form method="post" action="{% url 'excluir_grupo_despesas' grupo.id %}" style="display:inline;" onsubmit="return confirmarExclusao();">
                            {% csrf_token %}
                            <button type="submit">Excluir</button>
                        </form>
                        <form method="get" action="{% url 'alterar_grupo_despesas' grupo.id %}" style="display:inline;">
                            <button type="submit">Alterar</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>